logging:
  level:
    root: INFO
    com.example.chatserver: INFO
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/chatdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
#  chatserversecretaccesstokenchatserversecretaccesstokenchatserversecretaccesstoken -> encoding
  secretKey: Y2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  expiration: 3000 # token duration - ? ??