spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: redis-service
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB_HOST는 k8s의 Secret내의 key 이름과 일치
    url: jdbc:mysql://${DB_HOST}:3306/ordersystem?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.chatserver: INFO
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: INFO

jwt:
#  chatserversecretaccesstokenchatserversecretaccesstokenchatserversecretaccesstoken -> encoding
  secretKey: Y2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  expiration: 3000 # token duration - ? ??